// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxcxE5oWYfjayJWY8fm7HcSeBL65YIcEQ',
    appId: '1:1029811713951:web:13cd88244d2c61b2386faa',
    messagingSenderId: '1029811713951',
    projectId: 'doctors-931c0',
    authDomain: 'doctors-931c0.firebaseapp.com',
    storageBucket: 'doctors-931c0.appspot.com',
    measurementId: 'G-PLS9GE80X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRqSaPln0xsQcADJpc-X7NWjKBgYveDEk',
    appId: '1:1029811713951:android:e5ad84f73627b50f386faa',
    messagingSenderId: '1029811713951',
    projectId: 'doctors-931c0',
    storageBucket: 'doctors-931c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmrb-XaLF6axxP4_A1y_Ph0oRg9xlvu0',
    appId: '1:1029811713951:ios:a2dfd6ade9032b0d386faa',
    messagingSenderId: '1029811713951',
    projectId: 'doctors-931c0',
    storageBucket: 'doctors-931c0.appspot.com',
    iosBundleId: 'com.example.doctors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMmrb-XaLF6axxP4_A1y_Ph0oRg9xlvu0',
    appId: '1:1029811713951:ios:1ef62c6a6ede97f8386faa',
    messagingSenderId: '1029811713951',
    projectId: 'doctors-931c0',
    storageBucket: 'doctors-931c0.appspot.com',
    iosBundleId: 'com.example.doctors.RunnerTests',
  );
}
